### ISSUE TITLE
Nonce Error for Authenticated Users

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms-uploads#270]
Seeing sparse reports of a "Nonce Error" with the Uploads field with Authenticated Users.

---

Reference: https://wpninjas.kustomerapp.com/app/customers/596c4ad79236fa00114676c5/event/59757b37291ce90011c789f2

**Comment by Much2tall** [comment]
includes/ajax/controllers/uploads.php (L: 38)

Result of this check returning 'false':
check_ajax_referer( 'nf-file-upload-' . $field_id, 'nonce', false );

https://developer.wordpress.org/reference/functions/check_ajax_referer/

In the previous report of this, we found that the user had some database issues going on, but with a second File Upload Field on the Form, I was able to copy over the nonce from the "broken" Field and have it upload to the new one. This tells me that the function is returning false because of the first argument, not the second.

**Comment by polevaultweb** [comment]
My own investigations with this have found that the nonce created by FU for a field, is actually not the nonce passed back for the check for authenticated users. It seems the nonce is being replaced in the form. That was when looking at https://wpninjas.kustomerapp.com/app/customers/581714930b0ff4110031fa39/event/5949485f0e0528001192f3b0

So confused why the fix of replacing the fields worked (props @Much2tall!)

**Comment by polevaultweb** [comment]
This was happening for non authenticated users due to WC Total Cache https://wpninjas.kustomerapp.com/app/customers/582c70c2e58ad61100ec87bc/event/5977790ead3c380010fc33f9

**Comment by Much2tall** [comment]
Another report of this happening with an authenticated user: https://wpninjas.kustomerapp.com/app/customers/581714930b0ff4110031fa39/event/5949485f0e0528001192f3b0

**Comment by polevaultweb** [comment]
@Much2tall not a new report - same guy as https://github.com/wpninjas/ninja-forms-uploads/issues/270#issuecomment-317667881.

**Comment by Much2tall** [comment]
@polevaultweb Yes, same guy, but on a Form that had already been corrected for the error once before.
So, my solution of just replacing the Field with a new one isn't permanent, or at least not in this guy's case.

**Comment by polevaultweb** [comment]
This is likely due to Save Progress saving an old nonce. https://wpninjas.kustomerapp.com/app/customers/594bb22d0e052800119de021/event/59944f7535623400117c05bc

**Comment by polevaultweb** [comment]
@kstover @kjohnson is there anyway to not save certain model /view data?

**Comment by kjohnson** [comment]
@polevaultweb per our discussion, we probably needs to move any nonces outside of the field context and into a form context, which will avoid any Save Progress conflict.

**Comment by polevaultweb** [comment]
@kjohnson uh oh https://github.com/wpninjas/ninja-forms-save-progress/issues/66

**Comment by wpnzach** [comment]
Adding to top support issues, impacted users have a paid product that does not work.

**Comment by rbuschmeyer** [comment]
Customer/User here... we started seeing the Nonce errors you're working on in one of our forms and have had to remove the File Uploads field entirely.  The interesting thing is that other forms have continued to work, but they do not have the Save Progress buttons on them.  The one form we are seeing errors with is a multi-part one.

I'll be happy to help by providing logs/access to our site.

**Comment by polevaultweb** [comment]
@rbuschmeyer this is being fixed in the next version of Save Progress 👍

**Comment by rbuschmeyer** [comment]
Thanks.  No ETA on that release though?

 

--

Ryan Buschmeyer

C2K Consulting, LLC

**Comment by polevaultweb** [comment]
@kjohnson should be able to give you an idea of that

**Comment by kjohnson** [comment]
@rbuschmeyer currently preparing a release.

**Comment by rbuschmeyer** [comment]
Thanks, Kyle…

 

We are looking forward to getting File Uploads back into our forms.  We appreciate the help.

 

--

Ryan Buschmeyer

C2K Consulting, LLC

**Comment by kjohnson** [comment]
PR in Save Progress is merged. Closing issue.

**Comment by rbuschmeyer** [comment]
Good afternoon Kyle, I take it the update to Save Progress is released?  Are we clear to update and rest now?

--
Ryan Buschmeyer
C2K Consulting, LLC.
412.999.3394

**Comment by frankiekiely12** [comment]
Hi all! I came across this thread while searching for a solution to our own nonce error issue. I'm new to github so please forgive me if i've reopened something or I shouldn't be commenting here but if someone could point be in the right direction of help it'd be really appreciated?

**Comment by polevaultweb** [comment]
@frankiekiely12 best to shoot an email over to the Ninja Forms support :)

**Comment by frankiekiely12** [comment]
@polevaultweb Thank you so much mate!

**Comment by mvincik** [comment]
Hello,

I wanted to report back what I think might be the issue. I believe there is some security setup on the file uploads that generates a unique session code. When you have a caching plugin installed, it might be possible that a single code is being cached and served to many different people instead of one code per session. What I did to resolve the issue was exclude the page with the file upload from being cached. That seemed to have solved the issue. I haven't confirmed this with our development team but I do believe that this solved the issue one and for all.
